### ISSUE TITLE
Join quoted strings

### ISSUE THREAD

**Issue by Rik69** [MaiconSoft/DelphiBoostLib#1]
I like your DelphiBoostLib.

I want to use it to generate a SQL In query like : 

'One','Two','Number Three','It''s number 4'

I already have a TStringlist helper to do it, but maybe you have a fast solution with Boost.Strings

Thank you

Erik

**Comment by MaiconSoft** [comment]
Hi Erik, I glad you like DelphiBoostLib.
The Quoted is now supported.
Thank you for your suggestion.
